before_script:
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - apt-get install -y nodejs
  - apt-get install -y build-essential
  - npm install

start-up:
  script:
    - node bot.js